language: java
jdk:
- oraclejdk8

before_install:
- chmod 777 /home/travis/build/ramesharpu/SeleniumWebdriverMavenTestNGTravis/drivers/*

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
